### ISSUE TITLE
Allow outputting into yaml

### ISSUE THREAD

**Issue by SelfhostedPro** [knative-sandbox/kn-plugin-func#1015]
Hello, I'd like to be able to output any manifests that would normally get applied to a kubernetes cluster into a local file in order to deploy functions following GitOps principals. Is this something that is feasible or already exists? (I didn't see if when searching through issues)

**Comment by lance** [comment]
Hi @SelfhostedPro  - first - sorry for the latency in responding! You should track this PR where this feature has been proposed https://github.com/knative-sandbox/kn-plugin-func/pull/898

**Comment by lance** [comment]
There has been discussion around this in a couple of different areas - on cluster builds, service deployment, etc. Let's use this issue as a place to discuss what's needed, and to collate any new issues or PRs that get created as a result.

Currently, I am leaning towards the idea of a `--dry-run` flag for `func deploy` to generate yaml files.
