### ISSUE TITLE
On-Cluster build: Nodejs fails to deploy

### ISSUE THREAD

**Issue by jrangelramos** [knative-sandbox/kn-plugin-func#1025]
NodeJS function fails to deploy on cluster using Tekton Pipelines.

Given that tekton is installed and tasks are created (from git-clone, func-buildpack, func-deploy) as on https://github.com/openshift-knative/kn-plugin-func/blob/serverless-1.22.0/docs/guides/on-cluster-build.md 

... and func project is created, edited and pushed to git repo
```
$ func create -l node sample-func
...
# git work.. edits on func.yaml push to repo 
```

On func deploy. The following error is observed

```
$ func deploy
🕑 Creating Pipeline resources
🕕 Running Pipeline: Building function image on the cluster
Error: failed to run pipeline: function pipeline run has failed with message: 

sha256:26916085eb226d55f3b4694e7de7258ec75e782f3e53d1a6b401b731bb7a9b9f
sed: /workspace/source/func.yaml: No such file or directory

```

**Comment by jrangelramos** [comment]
A little more background.
It fails on the `func-buildpacks` tasks on the `results` step while trying to updata func.yaml on source workspace.

Per my inverstigations the source workspace (which is mounted and passed to the builder) is cleaned by the previous task (`create`)
https://github.com/boson-project/buildpacks/blob/main/buildpacks/nodejs/bin/build#L41

**Comment by zroubalik** [comment]
I think this has been resolved by using packeto buildpacks.

Please reopen if needed.
