### ISSUE TITLE
The `func invoke -f=http` sub-command uses from encoding not JSON.

### ISSUE THREAD

**Issue by matejvasek** [knative-sandbox/kn-plugin-func#1038]
I believe the `data` part should be send as s body of POST request.
The content-type should be set as standard HTTP header.
The other CE specific values (type,source,subject,time) should be ignored.

**Comment by lance** [comment]
> I believe the data part should be send as s body of POST request.

Yes - agree.

> The content-type should be set as standard HTTP header.

Specifically, we should use `application/json` unless otherwise specified by the user.

> The other CE specific values (type,source,subject,time) should be ignored.

We should not be using the cloudevents library at all for the HTTP requests, or attempting to approximate anything other than a standard HTTP POST.
