### ISSUE TITLE
OnClusterBuild: Allow PVC size specification

### ISSUE THREAD

**Issue by tvand** [knative-sandbox/kn-plugin-func#1049]
We use NetApp as a storage backend where the minimum PVC size allowed is 20MB. So during creation, the first run stalls because the 5MB default PVC cannot be created. It would be helpful to be able to override the default somehow.

**Comment by zroubalik** [comment]
This has been tracked here, let's continue there: https://github.com/knative-sandbox/kn-plugin-func/issues/851

@tvand this is a reasonable ask, are you willing to contribute this?

**Comment by tvand** [comment]
I have no real experience with Go.

**Comment by zroubalik** [comment]
There is never too late to start with Go :)
