### ISSUE TITLE
quay.io/boson/faas-nodejs-builder cleans build directory, so step func-buildpacks.results does not find func.yaml anymore

### ISSUE THREAD

**Issue by tvand** [knative-sandbox/kn-plugin-func#1050]
The Tekton task func buildpacks runs in three steps: prepare, create and results. 

When using the faas-nodejs-builder image, one of the last steps of the build is to clean the build directory (see https://github.com/boson-project/buildpacks/blob/main/buildpacks/nodejs/bin/build, lines 39-41)

This causes the results step to fail because func.yaml does no longer exist.

**Comment by lance** [comment]
Download the latest via `brew install func` or from https://github.com/knative-sandbox/kn-plugin-func/releases

**Comment by tvand** [comment]
We use the kn version delivered with Openshift 4.8. Can we simply upgrade?

**Comment by lance** [comment]
> We use the kn version delivered with Openshift 4.8. Can we simply upgrade?

Yes there should be no problem upgrading from a technical point of view.
