### ISSUE TITLE
TOC meeting planning 8 August 2022

### ISSUE THREAD

**Issue by salaboy** [knative-sandbox/kn-plugin-func#1064]
Let's use this issue to list topics that we want to bring up at the TOC meeting.

@lance @salaboy 

- [WG Update slides](https://docs.google.com/presentation/d/1RIZTwNxXi35CmZM8lmc8qF0LF7dxKMvMN-rMF1Ikmvg/edit?usp=sharing)

- Update on 1.0 work: https://github.com/orgs/knative-sandbox/projects/7
- Update on documentation: https://docs.google.com/document/d/1wBpBA76nfgqoN6vKje7g1n7milB8l5gQZfuE49_teAk/edit?usp=sharing  
- Maintainers track for KubeCon

**Comment by salaboy** [comment]
@lance, as we discussed in our triage meeting, some milestones that we might want to have (brain dump) :

- **1.0.0 Release Cut**:  10/1/22 - 10/7/22 
- ** Pre 0.99.0 Release**: 9/15/22
- **MVP Issues Closed**: 
  - 9/1/22: we should decide by this date if all the MVP issues will make it into the release or what are the things that we will not manage to get in
  - Current high-priority topics: 
    -  `func.yaml` structure refactor
    - `dry-run`: for now we will use `--target` from `kn`
    - `OnCluster Build`: this contains several small issues that are marked as MVP
- **Documentation Updates**
   - 9/1/22: we should have a definition of what needs to be updated
   - 9/24/22: we should have made all the changes, so they are ready to be included in the release cut
- **User testing / Workshop??**
  - It will be great to aim for 9/15/22 with a pre-release; maybe we can do a community thing? Maybe @csantanapr can help us out here. I met with `Daniel Oh` at JBCNConf he was also running a workshop with functions, maybe we can use some of that?

**Comment by lance** [comment]
@salaboy I am creating milestones in the github UI here https://github.com/knative-sandbox/kn-plugin-func/milestones?with_issues=no

**Comment by lance** [comment]
Meeting already happend
