### ISSUE TITLE
Document the --build flag for func run

### ISSUE THREAD

**Issue by lance** [knative-sandbox/kn-plugin-func#1085]
It's missing in this document https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/reference/commands.md

While at it, it would probably good to double check other commands and their parity with the documentation.

/kind good-first-issue

**Comment by lance** [comment]
Now that I've created this issue - I wonder if it's really needed. We have talked informally about letting the CLI help text be the actual documentation. The inconsistencies that exist may get fixed, but we'll soon find ourselves in another scenario where something is missing or old. Should we instead either 1) remove the existing reference doc, or 2) automate a build stage that does something like (pseudo code):

```
for $cmd in `func help` do
  `func help $cmd` > docs/commands/$cmd.txt
```

@knative-sandbox/kn-plugin-func-approvers  wdyt?

**Comment by lkingland** [comment]
I think your other PR which generates help text from the commands also closes this issue @lance
