### ISSUE TITLE
Add metacontroller func example to func-tastic

### ISSUE THREAD

**Issue by salaboy** [knative-sandbox/kn-plugin-func#1120]
An interesting example to add to the `func-tastic` repository would be a `func` implementing a metacontroller controller. 
I've already created an example here: https://github.com/salaboy/from-monolith-to-k8s/tree/main/kubernetes-controllers/metacontroller/func-conference-controller 

But this needs to be simplified to work without the need of having other services available. We can do a simple example by checking if www.google.com and www.ebay.com are online. 
If someone wants to work on a draft PR, I will happily help you to document and push the example to the `func-tastic` repository.

**Comment by lance** [comment]
I'm thinking I will create a metacontroller that monitors Knative Services having the label `functions.knative.dev=true` and update the service to have a new label `function.valid=true` or something else innocuous like that. WDYT is that too basic?
