### ISSUE TITLE
Help text in command prompt sometimes use functions and sometimes Functions

### ISSUE THREAD

**Issue by nainaz** [knative-sandbox/kn-plugin-func#1122]
![image](https://user-images.githubusercontent.com/36016404/179365614-4637da23-9b8f-490a-aee2-74a36d55a115.png)

Ask for consistency in writing Functions in the help command

**Comment by zroubalik** [comment]
So the preferred is `Functions`?

**Comment by zroubalik** [comment]
> So the preferred is `Functions`?

As @lance mentioned on #1128 :

>I think we should change all user-facing text to use "function" instead of "Function", as I would like to reserve the capitalized naming for any eventual custom resource that we may end up with. When referring to this theoretical Function resource, we can capitalize it. But for the somewhat abstract, shifting thing that is the output of the func CLI, I would prefer to simply use "function" and "function project"
