### ISSUE TITLE
func build with -i does not use given image name

### ISSUE THREAD

**Issue by gauron99** [knative-sandbox/kn-plugin-func#1125]
Using `func build -i docker.io/gauron/app:latest` doesnt create image named `docker.io/gauron/app:latest` but instead 
`image-registry.openshift-image-registry.svc:5000/default/app` (name gets overridden)

* **Reproduce**: 
`func create -l go`
`func build -i docker.io/name/app`

it looks to me like in `Build` function (client.go) the registry is populated with the openshift default registry and used in `DerivedImage` (look at image below)

![image](https://user-images.githubusercontent.com/49119790/179743827-58f04a9f-7764-4b55-a5a0-6aaa368191a3.png)
`f.Registry` is empty but `registry` is the default openshift registry right before the if statement (as indicated by the LOOK DEEP print) therefore the if is skipped and image is built without image flag

/kind bug

**Comment by lance** [comment]
Good catch!

**Comment by zroubalik** [comment]
@gauron99 nice, are you eager to fix this one? 😄
