### ISSUE TITLE
Question: do we want to support specific workload templates?

### ISSUE THREAD

**Issue by daisy-ycguo** [knative-sandbox/kn-plugin-func#1158]
Other than general language runtimes, do we want to support more specific workload templates in knative function? For example, Tensorflow or Pytorch. Do we want to support an extension mechanism to allow third party templates, just like [OpenFaaS store](https://github.com/openfaas/store)? Thank you.

**Comment by zroubalik** [comment]
Absolutely. We support more specific templates via https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/language-pack-providers/language-pack-contract.md#extensible-language-packs

This repo should probably host these: https://github.com/knative-sandbox/func-tastic

**Comment by salaboy** [comment]
As @zroubalik I totally see some PyTorch and Tensorflow examples in https://github.com/knative-sandbox/func-tastic

**Comment by daisy-ycguo** [comment]
Great to know that. I would like to contribute some Tensorflow or Pytorch template. I understand where to go. 
Thank you. @zroubalik @salaboy

**Comment by lkingland** [comment]
Thank you @daisy-ycguo , supporting these types of function workloads is one of our primary goals.  Please continue to let us know if there's anything we can do to help.
