### ISSUE TITLE
Function fails to build when registry and image keys are specified

### ISSUE THREAD

**Issue by pmbanugo** [knative-sandbox/kn-plugin-func#1159]
I went through the func.yaml docs to find info about the registry variable but I found nothing about it. If I specify a value for it, the cli fails to build the function. Here's what I tried:

For the the first run, the cli asks for my registry info which I specify and it updates func.yaml and builds the image. It only sets the `image` variable.

If I edit it and specify `registry: docker.io/pmbanugo`, and image is empty (i.e `image: ""`). I expected it to also build the project without asking me for registry info, but it prompts me for it. When I enter a value for the prompt, it generates a value for `image` but immediately exits with the error

```
Building function image
Error: registry name is required
```

So as long as I have a value set for registry and image it throws that error.

I'm running version 0.25.1

**Comment by pmbanugo** [comment]
![](https://media.giphy.com/media/azaMjwRFm0vjNSd51t/giphy.gif)

@lance Does that mean that it'll be available after the Tuesday release?

**Comment by lance** [comment]
> Does that mean that it'll be available after the Tuesday release?
Yes it should be in the next release.
