### ISSUE TITLE
Templates list command takes time to execute the command.

### ISSUE THREAD

**Issue by sudhirverma** [knative-sandbox/kn-plugin-func#1186]
`func templates --json` command takes time to display the output. If I add one medium size project repository it takes 40-50 seconds to display the output.

cc: @mohitsuman @lstocchi

**Comment by lance** [comment]
I am not seeing this behavior. (Note 0.3 seconds). Can you provide with some steps to reproduce this?

```
❯ time ./func templates --json
{
  "go": [
    "cloudevents",
    "http"
  ],
  "node": [
    "cloudevents",
    "http"
  ],
  "python": [
    "cloudevents",
    "http"
  ],
  "quarkus": [
    "cloudevents",
    "http"
  ],
  "rust": [
    "cloudevents",
    "http"
  ],
  "springboot": [
    "cloudevents",
    "http"
  ],
  "typescript": [
    "cloudevents",
    "http"
  ]
}
./func templates --json  0.03s user 0.01s system 107% cpu 0.035 total
```

**Comment by matejvasek** [comment]
@sudhirverma what repo did you use?

**Comment by matejvasek** [comment]
What about other commands? Do they run all right?

**Comment by matejvasek** [comment]
https://github.com/knative-sandbox/func-tastic takes 1.8 sec.

**Comment by sudhirverma** [comment]
> https://github.com/knative-sandbox/func-tastic

I added only this(https://github.com/knative-sandbox/kn-plugin-func) repo for testing.

**Comment by matejvasek** [comment]
@sudhirverma how did you added it? via envvar?

**Comment by sudhirverma** [comment]
I use command `func repository add func https://github.com/knative-sandbox/kn-plugin-func`

**Comment by matejvasek** [comment]
OK, I'll look into this.
But https://github.com/knative-sandbox/kn-plugin-func isn't really template repository.

**Comment by matejvasek** [comment]
`func repository add func https://github.com/knative-sandbox/kn-plugin-func` is not something that should be done.

**Comment by sudhirverma** [comment]
> `func repository add func https://github.com/knative-sandbox/kn-plugin-func` is not something that should be done.

yes but it allows me to add so I thought that could be a bug.

> https://github.com/knative-sandbox/func-tastic takes 1.8 sec.

it will increase the time if I add multiple repositories.

**Comment by matejvasek** [comment]
I'll try make it faster.

**Comment by lance** [comment]
> yes but it allows me to add so I thought that could be a bug.

It should perhaps validate the repo when adding, but that is not happens today. If you want to add a repo for testing purposes, you can try https://githbub.com/knative-sandbox/func-tastic. I see no real slowdown when this is added.

```
❯ ./func repo add functastic https://github.com/knative-sandbox/func-tastic

❯ time ./func templates --json
{
  "go": [
    "cloudevents",
    "http",
    "functastic/improve",
    "functastic/uppercase"
  ],
  "node": [
    "cloudevents",
    "http"
  ],
  "python": [
    "cloudevents",
    "http"
  ],
  "quarkus": [
    "cloudevents",
    "http"
  ],
  "rust": [
    "cloudevents",
    "http"
  ],
  "springboot": [
    "cloudevents",
    "http",
    "functastic/uppercase"
  ],
  "typescript": [
    "cloudevents",
    "http"
  ]
}
./func templates --json  0.08s user 0.05s system 108% cpu 0.120 total
```

**Comment by matejvasek** [comment]
I made some improvements: #1189

If it wouldn't be enough we can add caching, the `NewRepository` function is called unnecessarily often.

**Comment by matejvasek** [comment]
To reiterate, there are two problems:
* `NewRepository()` is not optimal for non-bare git repositories
* `NewRepository()` is called far to often

I created PR for the former. If needed we can address the latter.
