### ISSUE TITLE
Wrong error message reported in command `func templates --repository` when the repository link does not exist 

### ISSUE THREAD

**Issue by daisy-ycguo** [knative-sandbox/kn-plugin-func#1206]
When running `func templates --repository` and the repository does not exist, an error message is reported:
```
$ func templates --repository=http://github.com/boson-project/func-templates
Error: failed to get repository from URI ("http://github.com/boson-project/func-templates"): failed to clone repository: authentication required
```

The root cause is that repo `http://github.com/boson-project/func-templates` is changed to `https://github.com/boson-project/templates`. When I use the correct repo link, the templates are listed.

Expected behavior:
The error message should show message like "the repo does not exist"

**Comment by grafvonb** [comment]
@lance may I take over that?

**Comment by lance** [comment]
/assign @grafvonb 

Thanks!
