### ISSUE TITLE
Update Knative dependencies to latest for GA (1.8) release

### ISSUE THREAD

**Issue by salaboy** [knative-sandbox/kn-plugin-func#1218]
To join the Knative release train we need to make sure that we update `func` dependencies to knative latest dependencies. 
Following this commit as guideline: https://github.com/knative-sandbox/kn-plugin-func/commit/c7b1bce3695e20b9390e79c1a70f861d9a9f5ad6 

Do you expect any issues with this upgrade @dsimansk?

**Comment by dsimansk** [comment]
Last week I was playing with it a bit, and I was able to bump to current latest 1.7 without any issues. I'd say it's totally reasonable for GA.

There're a few other considerations related to latest Knative deps:
- Updating Go to 1.18
- Kubernetes deps are driven from knative.dev/pkg
  - It was causing some conflict with Tekton, but it's usually manageable through specific Tekton versions.

In addition, we should probably enable periodic update-deps action. As it provides a good feedback about any deps conflicts every day etc.
https://github.com/knative-sandbox/knobots/blob/main/deps-exclude.yaml#L4

**Comment by dsimansk** [comment]
The `func` should be ready for 1.8 release train with auto-update action enabled and the following complementary PRs: 
- [ ] #1245 - successful upgrade to Knative 1.7 and release
- [ ] #1262

**Comment by lance** [comment]
@dsimansk any reason to hold off on #1262 ?

**Comment by dsimansk** [comment]
> @dsimansk any reason to hold off on #1262 ?

IMO it's good to go. :)

**Comment by dsimansk** [comment]
To be noted, I've done a bit of manual version bumps and tweaks to unblock auto-update action (there was K8s version bump after Knative 1.7 release). It's running smoothly now. However, before GA we might want to check other modules and the overall footprint of deps to update and cleanup (if needed).

**Comment by lance** [comment]
Closing - fixed in https://github.com/knative-sandbox/kn-plugin-func/pull/1262
