### ISSUE TITLE
`make test` not working with fresh clone

### ISSUE THREAD

**Issue by menehune23** [knative-sandbox/kn-plugin-func#1222]
Running `make test` after a fresh clone of this repo produces the [attached output](https://github.com/knative-sandbox/kn-plugin-func/files/9508823/out.txt). Is there something I'm missing, or is this repo not designed to be contributed to from a Mac? CI seems to be passing for this command, and it's running Ubuntu 20.04. I'm running macOS 12.5.1 (Monterey) on an Intel-based Mac.

**Comment by lance** [comment]
Hmm - that's odd. I am on an M1 Mac with MacOS 12.5.1 and cannot duplicate this problem. What version of go are you using?

**Comment by matejvasek** [comment]
I just noticed mistake in code:
filesystem_test.go:234
```go
	result, err := filesystemFromRepo(uri)
	if err != nil {
		t.Fatal(t) // this hsould be t.Fatal(err)
	}
```
It causes incorrect err output, not failure itself.
@menehune23 please try re-running the test with fixed code so we can see actual error.

**Comment by matejvasek** [comment]
also those unittest should run on macOS Github action on each PR.

**Comment by menehune23** [comment]
Thanks for the quick response @matejvasek! I'll give it a try again with a later version of go (and with your code fix), when I get a chance

**Comment by menehune23** [comment]
OK, glad it was a local issue. I upgraded golang from 1.17 -> 1.19 and it works well now :)

**Comment by menehune23** [comment]
@matejvasek Went ahead and put up a PR for the fix you mentioned: https://github.com/knative-sandbox/kn-plugin-func/pull/1226. Figured it's a good way to get set up with a fork and sign the CLA and everything
