### ISSUE TITLE
On Cluster builds does not allow to override the namespace specified via CLI

### ISSUE THREAD

**Issue by jrangelramos** [knative-sandbox/kn-plugin-func#1229]
On Cluster builds does not allow to override the namespace specified via CLI. It only uses the ns from `func.yaml`.

For exmaple:
I have a node js functions on GH with a default namespace https://github.com/jrangelramos/node-fn/blob/main/func.yaml#L3
When I invoke deploy commands using
``` 
$ func deploy -n test-ns
```
It does not use the new namespace, so I'm forced to update the namespace on func.yaml and push it to git.
```
rror: failed to run pipeline: function pipeline run has failed with message: 

Warning: Current namespace 'test-ns' does not match function which is deployed at 'default' namespace
⬆️  Deploying function to the cluster
Error: knative deployer failed to get the Knative Service: services.serving.knative.dev "node-fn" is forbidden: User "system:serviceaccount:test-ns:pipeline" cannot get resource "services" in API group "serving.knative.dev" in the namespace "default"
```

**Comment by lkingland** [comment]
I believe this is now fixed in #1079 

See [test `Test_namespace` in cmd/deploy_test](https://github.com/knative-sandbox/kn-plugin-func/pull/1079/commits/62a9cd93957dbbae635027d0194351b4f0264a91#diff-0db3441ba1989aee9f35f591d4a6bc0411c323a00e28aa8d24fdf83e242b72caR626-R632) on that PR
