### ISSUE TITLE
`func create` should validate function name

### ISSUE THREAD

**Issue by matejvasek** [knative-sandbox/kn-plugin-func#1259]
As of now it's possible to create a function as `func create 42`.
However such a name causes troubles because it's not valid part of domain.
Calling `func create 42` should result int error.

**Comment by lance** [comment]
Hmm - I agree that `42` is probably not ideal for a function or service name. But I'm trying to find any text that documents this as an error in Kube itself. All formatting restrictions on names that I can find note an alphanumeric requirement, but don't prohibit fully numeric names. See: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names. In that reference, it talks about DNS-1123 naming restrictions which is what we are validating for here. https://github.com/knative-sandbox/kn-plugin-func/blob/abc3097d7563051913573f82cd084add9af8b421/utils/names.go#L29-L41

**Comment by matejvasek** [comment]
@lance the regex there seems to be wrong:
```
Error: knative deployer failed to deploy the Knative Service: admission webhook "[validation.webhook.serving.knative.dev](http://validation.webhook.serving.knative.dev/)" denied the request: validation failed: not a DNS 1035 label: [a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')]: metadata.name
```
note that the name must start with [a-z].

**Comment by lance** [comment]
> @lance the regex there seems to be wrong:
> 
> ```
> Error: knative deployer failed to deploy the Knative Service: admission webhook "[validation.webhook.serving.knative.dev](http://validation.webhook.serving.knative.dev/)" denied the request: validation failed: not a DNS 1035 label: [a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')]: metadata.name
> ```
> 
> note that the name must start with [a-z].

Good catch - I missed that when scanning the name requirements. Start AND end with [a-z]

**Comment by matejvasek** [comment]
@lance maybe the validation changed over time, hard to believe we would got it wrong.

**Comment by matejvasek** [comment]
@dsimansk @rhuss is it possible that validation changes?

**Comment by lkingland** [comment]
In PR #317, `k8s/names.go` was deleted and replaced with `util/names.go`.  During that replacement, the implementation was also changed from the original DNS1035 label validation to this DNS1123.  This PR changes it back.  Was that change in error, or are we missing something here?

**Comment by matejvasek** [comment]
Probably only @zroubalik knows.

**Comment by matejvasek** [comment]
@lkingland the new validation is more restrictive so it shouldn't break anything.

**Comment by matejvasek** [comment]
> @lkingland the new validation is more restrictive so it shouldn't break anything.

Of course with exception of existing function breaking the validation,
but such a function are broken from get go.

**Comment by zroubalik** [comment]
Interesting, I recall I did this and I am quite sure I checked the regex from some actual code in Knative. Probably from some validation webhook, not sure, Ican't recall correctly.
Or maybe I just f*cked it up? 💥  

Thanks for fix.

**Comment by lkingland** [comment]
Just so long as there's not some reason we can remember specifically why the less-restrictive version was needed!  Good stuff.
