### ISSUE TITLE
[usability] Help message for "kn faas" should be improved

### ISSUE THREAD

**Issue by rhuss** [knative-sandbox/kn-plugin-func#187]
The help messages are confusing or wrong.

For a quick summary, please see the end of this description.

-------------
`kn help`

```
...
Plugins:
  faas        Function as a Service plugin
....
```

This is a technical description not targeted to the user (who actually probably does not care much that this is a "plugin"). Also, the header already indicates that this is a plugin.

Suggestion:

```
  faas       Scaffold, build and deploy functions
```
----------------

`kn faas help`

```
Function as a Service

Create and run Functions as a Service.

Usage:
  faas [command]

Available Commands:
  build       Build an existing Function project as an OCI image
  completion  Generate bash/zsh completion scripts
  create      Create a new Function, including initialization of local files and deployment
  delete      Delete a Function deployment
  deploy      Deploy an existing Function project to a cluster
  describe    Describes the Function
  help        Help about any command
  init        Initialize a new Function project
  list        Lists deployed Functions
  run         Runs the Function locally
  version     Print version.  With --verbose the build date stamp and commit hash are included if available.

Flags:
  -h, --help      help for faas
  -v, --verbose   print verbose logs

Use "faas [command] --help" for more information about a command.
```

* What is "Function as a Service" ? Should we just call it function ? (or at least as "Function-as-a-Service" to make a single term). I think that the `as a Service` is more confusing than it helps as it tells *how* the function is created and managed from a backend PoV, not really from a user's perspective. For a user it's really just a "function", regardless of how its operated. (Saying that one might even reconsider the "faas" command on its own and whether something like "func" wouldn't make more sense ? But this is yet another discussion)
* "Create and run Functions as a Service" --> "Manage and run Functions" (its also deleting and listing)
* "faas [command]" is wrong. It should be "kn faas [command]". This might be a general issue of the way how we do the inlining so might be possible to solve on the kn level. Still its wrong here, same as in the usage message in the last line.
* "Build an existing Functions project as an OCI image"
   - Why "Function" with capital "F" ?  If its to pronounce the concept, then consequently this should be "Function as a Service". But for readability reasons and to avoid a question mark when reading this, I suggest to keep it lower case
  - "existing Function project": I don't think this detail is necessary on this level. I would just remove this.
  - "OCI image" is not important for a functioning user which supposedly doesn't really want to care about the deployment format. I don't think that this implementation detail should shine through here.
* "completion", "help" and "version" should be put into a separate group (like in the top-level "kn") to keep full focus on the function workflow.
* "Create a new Function, including initialization of local files and deployment": Same comments as above, + "new" is redundant to "create", + too many technical details on this level. Also, I thought that "create" and "init" should have been folded into a single command? From the description alone it is not clear what the difference is between "create" and "init".
* "Delete and Function deployment" --> "Undeploy a function" ? (so maybe even rename the command itself, as delete might be confused with deleting the project itself ?)
* "help about any command" --> Remove the entry here, it's redundant with `--help`. `kn help` works, but is not listed on the help page
* "Lists deployed Functions" 
  - Remove "s" as this is an imperative like in "Create"
  - would remove the "deployed", this detail can be added to the subcommand itself.
* "Runs the Function locally"
  - "Runs" -> "Run"
* Version has far too many details. These should be only printed for "kn version --help".
---------------
I'm stopping here (not diving into the individual help pages), so that we can improve the help pages in an incremental fashion.

But I think we should already address/reconsider some fundamental questions:

* How should we name the _functionality_ itself (pun intended):
  - "Function" as a name (which would imply more a keyword like "func")
  - "Function-as-a-Service" which then also leads to "faas" as subcommand. Thinking again a bit more about this, I'm really not so sure that we expose this implementation detail (as I consider this) to the user. Its also not technically correct, because what is actually the *service* that is running our function? It's a container, so calling the OCI runtime a the 'service' for running the function is a fancy way of rebranding things. Regardless, I wouldn't expose this detail as part of the name, just to avoid exactly this kind of discussion which is not relevant to the user. She only cares about her code (and the _service_ is that we hide all the details).

* We should fix the confusion with "create" and "init" on this level. Also, a longer example of a complete workflow on the top-level would be super helpful (even `odo` does this).

* It all might sound a bit like nit-picking on a high level (one of my strong expertise ;-), but I firmly believe, that having a good and consistent help and usage message is an often underrated but very important feature, as this is usually the first contact with any CLI tool. Documentation only comes second (unfortunately). I would invest in this even before releasing DP.

**Comment by lance** [comment]
@rhuss thanks for the great feedback. Some responses below...

> What is "Function as a Service" ? Should we just call it function ? 

I agree that this phrasing is terrible for the several reasons you state. I won't comment on other related points you made around this, but overall am in agreement.

> "faas [command]" is wrong. It should be "kn faas [command]". This might be a general issue of the way how we do the inlining so might be possible to solve on the kn level. Still its wrong here, same as in the usage message in the last line.

I think this should be tackled in `kn` if possible. Ideally, this CLI should be able to stand alone so that non-OpenShift users can take advantage of it. It wouldn't make sense to have `kn` in that case.

> "Build an existing Functions project as an OCI image" 

Yes agree re: the implementation seeping through. Regarding the 'F' - I think the intent was to have "Function" as a formalized concept that when referred to with a capital F indicated we are talking specifically about Serverless Functions and not some random function. But I do agree it's odd.

> "completion", "help" and "version" should be put into a separate group (like in the top-level "kn") to keep full focus on the function workflow.

Very good point. 

> Also, I thought that "create" and "init" should have been folded into a single command? 

Yes - this just didn't happen before test day code freeze.

Overall great feedback. Thanks again.

**Comment by rhuss** [comment]
@lance let me fix the easy things (PR are coming) and create issues for the larger one.

**Comment by lance** [comment]
@rhuss I believe most if not all of your concerns here have been addressed in one way or another. The top level help for `kn func` now looks like this.

```console
❯ kn func help
Serverless functions

Create, build and deploy functions in serverless containers for multiple runtimes on Knative

Usage:
  func [command]

Examples:

# Create a node function called "node-sample" and enter the directory
kn func create myfunc && cd myfunc

# Build the container image, push it to a registry and deploy it to the connected Knative cluster
# (replace <registry/user> with something like quay.io/user with an account that have you access to)
kn func deploy --registry <registry/user>

# Curl the service with the service URL
curl $(kn service describe myfunc -o url)


Available Commands:
  build       Build a function project as a container image
  completion  Generate completion scripts for bash, fish and zsh
  create      Create a function project
  delete      Undeploy a function
  deploy      Deploy a function
  describe    Show details of a function
  help        Help about any command
  list        List functions
  run         Run the function locally
  version     Show the version

Flags:
  -h, --help      help for func
  -v, --verbose   print verbose logs

Use "func [command] --help" for more information about a command.
```

Can this issue be closed, and if we need to iterate further on the UX, create targeted, smaller issues?
