### ISSUE TITLE
[feat] Missing a runtime list command

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/kn-plugin-func#195]
**Is your feature request related to a problem? Please describe.**
The `kn faas` command is missing a subcommand to list all the available runtimes, with the list of supported triggers too. In order to find out the available runtimes, i need to run `kn faas create --help`

**Describe the solution you'd like**
A command like `kn faas runtimes` or something similar (feel free to bikeshed on the name) to list the matrix of supported runtimes/triggers

**Comment by lance** [comment]
Closing as this has been covered by https://github.com/knative-sandbox/kn-plugin-func/pull/490 and other related PRs
