### ISSUE TITLE
[feat] Make use of known-to-be-existent stuff on Openshift

### ISSUE THREAD

**Issue by markusthoemmes** [knative-sandbox/kn-plugin-func#196]
**Describe the solution you'd like**
I'd love if I wouldn't have to deal with the fact that we're building images when running on Openshift at all. Wouldn't it be cool if one could just do `kn faas deploy` on an Openshift cluster without additional setup (i.e. dockerhub accounts etc.).

We discussed briefly how it's non trivial to talk to the Openshift internal-registry, but maybe we can salvage Openshift builds (and their binary input feature) to build images on the cluster and into the registry on the fly.

**Comment by lance** [comment]
@markusthoemmes I think this should be covered by our On Cluster Builds FT - potentially by TP.

**Comment by omerbensaadon** [comment]
Checking on this, can this issue be closed?

**Comment by zroubalik** [comment]
@omerbensaadon this is still not resolved

**Comment by lkingland** [comment]
> Wouldn't it be cool if one could just do kn faas deploy on an Openshift cluster without additional setup (i.e. dockerhub accounts etc.)

Yes.  That is indeed a goal!  For non-openshift as well.

**Comment by lance** [comment]
Closing as a duplicate of #620

**Comment by nainaz** [comment]
related to #620
