### ISSUE TITLE
Group main help message to put important commands to the top

### ISSUE THREAD

**Issue by rhuss** [knative-sandbox/kn-plugin-func#215]
I.e. the `version`, `help` and `completion` commands should be put into a separate section below the main commands. This can be achieved with the same technique as found for `kn` that uses advanced templating techniques from Cobra.

**Comment by grafvonb** [comment]
Hi @rhuss! Are you still working on this issue? If not, I would try to solve it, based on your suggestion to use your code and ideas from `kn`. I have some years of knowhow in go, Cobra, Kubernetes&Co. I have already briefly analysed your solution for `kn` and the question would be if we need exactly the same for `func` or maybe something simplified.

**Comment by zroubalik** [comment]
@grafvonb would be great if you can take a look on this.

**Comment by grafvonb** [comment]
Great, I'll take over.

**Comment by zroubalik** [comment]
@grafvonb any update on this please?

**Comment by lance** [comment]
Would love to see this in 1.0

**Comment by grafvonb** [comment]
@zroubalik I will submit my status this coming weekend. Is that ok for you?

**Comment by zroubalik** [comment]
@grafvonb sure, thanks a lot!

**Comment by grafvonb** [comment]
@zroubalik as discussed, I have checked the context, made a fork and run the core tests successfully on my Mac locally. So I am ready to start developing this change. Two questions before I start:

1. My plan is to reuse the parts of the code from the `fn` project, as suggested by @rhuss. I just don't want to reinvent the wheel. Is that ok with you from a technical and legal perspective?
2. @lance What is the schedule for the 1.0? I would like to make a schedule as I am doing this in my spare time.

Thanks a lot!

**Comment by zroubalik** [comment]
@grafvonb I suppose you meant `kn` project (https://github.com/knative/client/)? Then it is completely fine to use it and it is actually preferred :) 

Thanks for contributing this!

**Comment by grafvonb** [comment]
Yes, exactly `kn`, as you can see, I think about functions only ;).

**Comment by zroubalik** [comment]
> Yes, exactly `kn`, as you can see, I think about functions only ;).

![approve](https://user-images.githubusercontent.com/726523/182096241-3bf265de-f3ea-493f-919a-007383d839a0.gif)

**Comment by lance** [comment]
@grafvonb you can track our progress towards 1.0 here https://github.com/orgs/knative-sandbox/projects/7/views/13

**Comment by grafvonb** [comment]
Done by https://github.com/knative-sandbox/kn-plugin-func/pull/1152
