### ISSUE TITLE
Use `kn function` in help message when run as a plugin to kn

### ISSUE THREAD

**Issue by rhuss** [knative-sandbox/kn-plugin-func#216]
This requires two things:

* Set a flag when the `init()` method is called when the plugin registers itself
* Evaluate that flag when creating the root command. Unfortunately by standard Cobra mean it is not possible to set a two-level command name directly. Therefor we need to adjust the generation of the help messages, but we need to do this anyway because of #215

**Comment by lance** [comment]
@lkingland I believe https://github.com/knative-sandbox/kn-plugin-func/pull/705 has a number of changes that address this issue. Below is a list of all of the `func` sub-commands. I've checked which ones I think are covered by your PR, or already doing this correctly today, or where it's irrelevant.

- [ ] build       Build a function project as a container image
- [x] completion  Generate completion scripts for bash, fish and zsh
- [x] config      Configure a function
- [x] create      Create a Function Project
- [ ] delete      Undeploy a function
- [ ] deploy      Deploy a function
- [x] invoke        Emit a CloudEvent to a function endpoint
- [ ] help        Help about any command
- [x] info        Show details of a function
- [ ] list        List functions
- [ ] repository  Manage installed template repositories
- [ ] run         Run the function locally
- [x] version     Show the version

Let's use this list to keep track of this work.

**Comment by lkingland** [comment]
All the commands will now be passing their help text through a template preprocessor which will replace any instance of `{{.Name}}` with the effective command name (`func` or `kn func`).  So long as we are sure to use this variable in our future command help text expansion, we should be GTG here.
