### ISSUE TITLE
Add additional labels to function deployments

### ISSUE THREAD

**Issue by lance** [knative-sandbox/kn-plugin-func#261]
Currently, when we deploy a function as a knative Service, we add two labels `boson.dev/function=true` and `boson.dev/runtime=[runtime]`. It might be also useful to add the builder used to create the image. Since the image name and digest are already captured in the `Service` definition, I don't think that's necessary to add as a label. But would it make sense to allow for a  `labels` section in `func.yaml` which would allow developers to easily apply labels to their functions. E.g.

```
labels:
  type: telegram.message
  botId: language.filter
```

What do you all think?

**Comment by lkingland** [comment]
Seems like a good idea to me, if there is the need for it now.  Labels is also a very generic concept so our abstraction remains intact (just like our discussion around Secrets).

**Comment by zroubalik** [comment]
Agree, good idea.

**Comment by lance** [comment]
> It might be also useful to add the builder used to create the image

I tried this, but labels have restrictions on the characters that can be used, and a slash as in `quay.io/boson-project/some-builder` is not acceptable.
