### ISSUE TITLE
Consider adding func to homebrew so it can be easily installed standalone

### ISSUE THREAD

**Issue by lance** [knative-sandbox/kn-plugin-func#268]

**Comment by zroubalik** [comment]
Is this going to be standalone `func` command or added `func` plugin to the upstream `kn` published by Homebrew?

**Comment by lance** [comment]
@zroubalik I think that `kn` is already available via homebrew - obviously without `func`. :smile: We could try and add it as a plugin for that distribution. I'm not sure if the upstream `kn` includes plugins for the homebrew distribution, maybe @rhuss would know. In any case, I was really talking about `brew install func`.

**Comment by rhuss** [comment]
We are thinking to introduce a repository for installing plugins via https://github.com/knative/client/issues/397#issuecomment-788998071 

The point is that if you install func standalone it needs to be called `func`, but for kn as plugin it has to be `kn-func`. But maybe the Brew formula syntax is rich enough to support creating symlinks ?

**Comment by lance** [comment]
Related: https://github.com/knative-sandbox/kn-plugin-func/issues/441

**Comment by lance** [comment]
@rhuss @dsimansk this is done, right?

**Comment by rhuss** [comment]
Right, but currently 0.18 is the latest release in https://github.com/knative-sandbox/homebrew-kn-plugins --> https://github.com/knative-sandbox/homebrew-kn-plugins/blob/main/func.rb#L4

In case of a func release this repo needs to be updated manually (by sending a PR with the updated version numbers, plus potentially copying over the original version to a `func@0.18.rb` like done for the version 0.17.

**Comment by lance** [comment]
> In case of a func release this repo needs to be updated manually (by sending a PR with the updated version numbers, plus potentially copying over the original version to a `func@0.18.rb` like done for the version 0.17.

OK - I'm going to close this in favor of an issue to do this
