### ISSUE TITLE
Add YAML schema for func.yaml

### ISSUE THREAD

**Issue by zroubalik** [knative-sandbox/kn-plugin-func#336]
We should create a schem for `func.yaml`, this could help with the validation and easier editing of the file in IDEs (values suggestion).

https://developers.redhat.com/blog/2020/11/25/how-to-configure-yaml-schema-to-make-editing-files-easier/

**Comment by zroubalik** [comment]
https://github.com/SchemaStore/schemastore/pull/1787

**Comment by lance** [comment]
@zroubalik this can be closed now, correct?

**Comment by zroubalik** [comment]
@lance 90% done. I will close it once the schema for labels and envs is done.
