### ISSUE TITLE
func deploy command fails to push image to registry on Windows machines

### ISSUE THREAD

**Issue by jrangelramos** [knative-sandbox/kn-plugin-func#354]
`deploy` command fails to push the image to the registry. I notice a strage behavior while trying different options. When you run `func deploy` without verbose mode it displays the message indicating gives you the impression it is pushing like this:
```
PS C:\Users\User\functions\gofunc> func deploy -b=false

←[1A←[K   Pushing function image to the registry
←[1A🕘 ←[1B
```
but it keep stuck forever, until you hit enter and get the following:
```
PS C:\Users\User\functions\gofunc> func deploy -b=false

←[1A←[K   Pushing function image to the registry
←[1A🕘 ←[1B
Password: Error: failed to get credentials: The handle is invalid.
``` 

When running in verbose mode it requires user, but it fails immediatelly after entering the username without giving you change the input the password
```
PS C:\Users\User\functions\gofunc> func deploy -b=false -v
Pushing function image to the registry
Username: jrangelramos
Password: Error: failed to get credentials: The handle is invalid.
PS C:\Users\User\functions\gofunc>
```

Tried from a different machines, VM and physical one also got this error for the same scenario above:
```
C:\Users\solcp>func deploy -p functions\nodefunc -b=false -v
Pushing function image to the registry
Username: jrangelramos
Password: Error: failed to get credentials: Identificador inválido.
````
note: (Identificador inválido -> Invalid identifier)

**Comment by lance** [comment]
Fixed in https://github.com/knative-sandbox/kn-plugin-func/pull/459
