### ISSUE TITLE
func.yaml and environment variable security

### ISSUE THREAD

**Issue by evanshortiss** [knative-sandbox/kn-plugin-func#357]
I'm opening this issue for discussion of best practices surrounding environment variables defined in the `func.yaml`. 

I didn't think much about this initially, but noticed that my func.yaml is included in the built container image. This isn't a big deal *unless* you're defining things like API Keys and SASL username/password in the environment. I was defining a username/password in the func.yaml and uploaded it to a public registry 😅

Does it make sense to strip the `env` field from the func.yaml, or omit the func.yaml (if that's even possible) from built images? I'm thinking how it can be better on the "secure by default" front.

**Comment by lance** [comment]
I think we should just not include func.yaml in the image. It should be easy to filter it out in the buildpack

**Comment by lance** [comment]
Closing: fixed in https://github.com/boson-project/buildpacks/pull/105
