### ISSUE TITLE
Support aarch64 macOS

### ISSUE THREAD

**Issue by matejvasek** [knative-sandbox/kn-plugin-func#377]
As far as I know we are not building binaries nor buildpack images for aarch64 macOS. Do we want it?

**Comment by matejvasek** [comment]
@boson-project/core wdyt?

**Comment by zroubalik** [comment]
I don't think that it is something that we need right now, but in a long term it is good to support this architecture. Btw `kn` doesn't provide this arch yet, so I guess the process should start there.

**Comment by lance** [comment]
Agree that it's something to anticipate, but not to do just yet.

**Comment by rhuss** [comment]
+1 for supporting the new Apple Silicon machines, but as darwin-amd64 still works for macOs regardless of architecture, I also think this does not need to be of high priority.
