### ISSUE TITLE
Contributor's guide link in README is a 404

### ISSUE THREAD

**Issue by julz** [knative-sandbox/kn-plugin-func#427]
I would have just fixed this, but I can't actually find a contributor's guide or DEVELOPMENT.md to update it to :). We should add one.

**Comment by lance** [comment]
> We should add one.

:100: all I can say is that sometimes links are aspirational. :)

**Comment by lkingland** [comment]
+1 for aspirational hyperlinks.  Good band name?

**Comment by lance** [comment]
As things come up in places, we should note them here to be added to the guide. For example: https://github.com/knative-sandbox/kn-plugin-func/pull/429#issuecomment-883637742
