### ISSUE TITLE
Make `func` easy to install and invoke from within CLI

### ISSUE THREAD

**Issue by omerbensaadon** [knative-sandbox/kn-plugin-func#441]
## Description: 
There should be a relatively simple "happy path" to installing the `func` plugin. 

---

## Story
```
As Perry the Platform Admin
I want to install the func plugin 
So that I can assess whether it is right for my needs 
```

## Acceptance Criteria
- [x] Perry can install using a binary 
```
GIVEN I have the downloaded the binary for the func plugin 
WHEN I place the the binary in the ~/.config/kn/plugins directory
THEN I can run `kn func` and see a help message 
```

- [ ] Perry can install using homebrew 
```
GIVEN I have typed "brew install knative-sandbox/kn-plugins/func" into my CLI
WHEN I hit enter
THEN the operation succeeds without error 
AND I can run `kn func` and see a help message 
```

## Known Issues and Considerations: 
This issue may be dependent on https://github.com/knative/client/issues/1399

**Comment by lance** [comment]
@omerbensaadon I think this can be closed and considered complete. WDYT?

See: https://github.com/knative-sandbox/homebrew-kn-plugins

**Comment by omerbensaadon** [comment]
If you /lgtm #539
