### ISSUE TITLE
Create builder images that are neutral and hosted 

### ISSUE THREAD

**Issue by omerbensaadon** [knative-sandbox/kn-plugin-func#446]
~~Blocked by: https://github.com/knative-sandbox/kn-plugin-func/issues/445~~
---

### Story
```
As Eddie the Existing Vendor
I want to ensure func runs on a neutral "stack"
So that efforts going into creating func is not geared toward any one vendor in particular
```

### Acceptance Criteria
```
GIVEN I run `kn func build` on an existing func project
WHEN the OCI function image is created as a result of `kn func build`
THEN I can inspect the image to ensure it is built on a Paketo buildpack
```

Here is the list of supported runtimes and their status regarding paketo builders. If checked, the paketo builders are in use.

- [x] go
- [x] node
- [x] rust
- [x] springboot
- [x] typescript
- [x] #977
- [x] #978

**Comment by lance** [comment]
There has been some progress on this, but it's not ready for closing yet. Currently we are moving to docker://ghcr.io/boson-project for a container registry. The registry contains two buildpacks - one for TypeScript and one for Go. You can find those buildpack images here: https://github.com/orgs/boson-project/packages

In the `func` binary, the TypeScript, Node.js and Go built in templates are now using paketo builders and the aforementioned buildpacks.  For example, the Go CloudEvent language pack.

https://github.com/knative-sandbox/kn-plugin-func/blob/1172a85c80f834ff3958073bc36ff4a5173c9de6/templates/go/events/manifest.yaml#L1-L8

For `MVP` we need to determine what additional built in language packs we want. I suspect Python and Java are high on the list.

**Comment by omerbensaadon** [comment]
Checking in on this... any updates Lance? 

Should this be on the roadmap?

**Comment by lance** [comment]
> Checking in on this... any updates Lance?

We have Go, Rust, Node.js and TypeScript all using Paketo builders. I believe that @salaboy is working on Paketo builders for the SpringBoot templates and @matejvasek is working on the same for Quarkus. Can you guys confirm? Once these are done, this can be closed.

> Should this be on the roadmap?

Sure - it's just the Quarkus and SpringBoot work that remains.

**Comment by lance** [comment]
**Update**
Here is the list of supported runtimes and their status regarding paketo builders. If checked, the paketo builders are in use.

- [ ] go
- [ ] node
- [ ] python
- [ ] quarkus
- [ ] rust
- [ ] springboot
- [ ] typescript
