### ISSUE TITLE
Provide interactive selection of project templates on `func create`

### ISSUE THREAD

**Issue by lance** [knative-sandbox/kn-plugin-func#453]
## Current behavior
When creating a new project, a function developer needs to know in advance what templates and runtimes are available. This information exists in the `--help` output. But the user needs to then remember that when typing the create command. If she has a lot of custom language pack repositories installed, the list of options could be quite long and names may not be intuitive.

## Proposal
A function developer should have an interactive CLI experience when creating a new project, similar to that which they experience when configuring a project with `kn func config`. The CLI should provide the user with a list of available runtime/template combinations, and allow her to select the one they want when the `--template` and/or `--runtime` flag is not provided. (Note that in https://github.com/knative-sandbox/kn-plugin-func/issues/451 there is a suggestion to combine these two flags, which would make the implementation of this feature simpler).

---

## Acceptance critera
```
GIVEN a function developer wants to create a new project
WHEN they type `kn func create <project name>`
THEN they are presented with an interactive prompt allowing them to select a template
```

**Comment by lkingland** [comment]
In keeping with the unix philosophy of small, focused, but perhaps most importantly composable commands; I am not sure that the _default_ action should be interactive prompts.  This interfere with he standard usage pattern of command line tools.   Some would go so far as to argue that interactive prompting has no place in a CLI and should instead be offered elsewhere such as web admin consoles or native apps.  I would stop short of this extreme reaction, and instead propose a middle way.   With a helpful error message on an unsuccessful command which instructs the user to invoke the command with the `--confirm (-c)` option for an interactive prompt.  This preserves the sacrosanct CLI experience, encourages learning it, while offering a simple upgrade path to interactivity.   So for example, following in the footsteps of the only other CLI tool we have a high liklihood of all developers also being familiar with: `git`, would it be acceptable to have something similar to the following experience?
```console
$ func create --runtime go --template invalid-template
usage:  func create [flags] <name>
Error:  The template 'invalid-template' was not found for runtime 'go'.  
  Available templates for this runtime are:
    http
    events
To see a list of all templates in all runtimes, see the `templates` (TODO)
To run this command in interactive mode, use --confirm (-c):
  func create -c
$
```
To play around with this proposed paradigm, please see #514 where it seems rather intuitive, with the exception being that by default help text is displayed for the root command, whereas here we do not have that option (there are no root commands) so the help which informs the user of the `-c` option would have to bee in the error text as well as `--help` to ensure the new user sees it.

**Comment by lkingland** [comment]
By the way, completing this issue will require adding prompts/confirmation to the command, necessitating a minor refactor, such that we might as well go "all the way" and prompt for runtime and name as well.
