### ISSUE TITLE
`func create` defaults to Node

### ISSUE THREAD

**Issue by omerbensaadon** [knative-sandbox/kn-plugin-func#488]
## Current Behavior
When I do `func create` a Node project gets created 

## Desired Behavior 
It would be nicer if the CLI prompted me to pick a runtime and showed me what runtimes were available. 

I'm actually still unsure what the desired behavior would look like. it could either be... 

``` 
GIVEN I have typed func create
WHEN I hit enter 
THEN the func CLI let's me know I must use the -l flag 
AND lists the currently supported runtimes
```
OR 
```
GIVEN I have typed func create
WHEN I hit enter 
THEN the func CLI prompts me to pick a language runtime 
AND lists the currently supported runtimes
```

**Comment by nainaz** [comment]
this can be closed now. It is being done through #573

**Comment by lance** [comment]
Pretty sure the behavior requested here was added in https://github.com/knative-sandbox/kn-plugin-func/pull/547
