### ISSUE TITLE
Progress information is confusing

### ISSUE THREAD

**Issue by rhuss** [knative-sandbox/kn-plugin-func#504]
Actually it looks like that `kn func deploy` (that still seems to include a build step) prints out:

![image](https://user-images.githubusercontent.com/99080/131848382-0190122f-7561-4d9c-bf43-418651377b1f.png)

but eventually ends up with 

![image](https://user-images.githubusercontent.com/99080/131848437-ec81b214-0d21-44e3-a7ee-bde077ba5d97.png)

Note that the "Build part" has been completely removed. It is generally confusing to remove parts of a progress log, so you should either print it step by step (maybe even a timestamp might be helpful to see how long it took) and keep it or at least remove also the last progress step when done. Otherwise, when coming back to the output you are not sure what has been really done. Also not sure how well this works when redirection the output in a file (which typically happens also in a CI context).

Also, note the typo in "Deployin". 

Also cool would be to have the URL is a separate line so that you quickly copy it into the clipboard by double-clicking that line.

**Comment by lance** [comment]
> Also, note the typo in "Deployin".

https://github.com/knative-sandbox/kn-plugin-func/pull/501

**Comment by lkingland** [comment]
the `-v` flag enables standard, scrolling output without control characters.  Also note this is the default if the command is being run not in an interactive terminal (such as a cron job, etc).

**Comment by lance** [comment]
@rhuss I actually think this issue _is_ stale, and could probably be closed. In https://github.com/knative-sandbox/kn-plugin-func/issues/555 and https://github.com/knative-sandbox/kn-plugin-func/issues/552 we discussed build and deploy usability quite a bit, and have landed changes to the output in https://github.com/knative-sandbox/kn-plugin-func/pull/537.

Overall, we made a few efforts to really clean up the progress information when building.

In addition, we are starting to address some of usability concerns around the intersection of the `build` and `deploy` commands. For example, in https://github.com/knative-sandbox/kn-plugin-func/pull/681 we now support a `--push` flag on the `build` command.

I recommend that we close this issue, now that some of the output/behavior of the CLI has changed. If there are concerns you have with the new behavior we can open a new issue with specific details around desired usability changes. WDYT?

**Comment by rhuss** [comment]
yes, sure. I was not aware that there has been changes elsewhere. If I find something odd I can still create a new issue.
