### ISSUE TITLE
`func deploy` registry options from command line (`-r`) should take precedence over registry on `func.yaml`

### ISSUE THREAD

**Issue by jrangelramos** [knative-sandbox/kn-plugin-func#506]
When you build a project using a testing repository that repo get saved on func.yaml.
Then when you use deploy command the specifying a different repository, func honor (func.yaml) and does not uses the specific setting passed on command line

```
$ kn func build -r localhost:5000/test
   🙌 Function image built: localhost:5000/test/myfunc:latest
$ kn func deploy -r quay.io/jrangelramos -v
Building function image
...
Pushing function image to the registry
The push refers to repository [localhost:5000/test/myfunc] (100%)
...
```

I think a command line options should take precedence in this case.

**Comment by zroubalik** [comment]
The same behavioiur for `func build`
