### ISSUE TITLE
Superfluous headers in go template

### ISSUE THREAD

**Issue by omerbensaadon** [knative-sandbox/kn-plugin-func#511]
@lkingland told me to submit this issue. 

(basically, if you type anything other than "OK" the container errors out)

**Comment by matejvasek** [comment]
@omerbensaadon could you please write more details?

**Comment by matejvasek** [comment]
Is this caused by setting content-length?

**Comment by omerbensaadon** [comment]
@matejvasek I think that's right yes. 

If you replace OK with anything else it just errors out since (I think because it's longer than 3 characters?
