### ISSUE TITLE
The `FUNC_REGISTRY` environment variable overrides image in `func.yaml`.

### ISSUE THREAD

**Issue by matejvasek** [knative-sandbox/kn-plugin-func#527]
The `FUNC_REGISTRY` environment variable should be only used if image registry is not explicitly set in `func.yaml`.

Right now the envvar overrides image registry in `func.yaml` upon build. So if the envvar points to let say `quay.io` and user wants to change that in `func.yaml` to `docker.io`, it's not possible because the image will be overwritten.

**Comment by shinigambit** [comment]
@matejvasek  mind if I have a crack at it?
