### ISSUE TITLE
Make sure users don't kill `func build`

### ISSUE THREAD

**Issue by omerbensaadon** [knative-sandbox/kn-plugin-func#552]
# Context
When we interviewed users, many of them watched `func build` hang for quite awhile... some (at least one) mentioned that they would probably cancel the process altogether given how long it took. 

This can probably be delivered by setting `func build` to run in verbose by default, but **a better user experience would be aligning to something similar to what `kn quickstart` does** which is to create some output for each smaller step within the process so users know the process is still running.

# Story 

**As Deandra the Developer**
**I want** to be assured that func is still running
**And I want** to know that the first time this runs it may take quite awhile 
**So that** I don't assume the command is hanging 

# Acceptance Criteria
- [ ] Make sure I don't kill `func build`
```
GIVEN I have already run func create myfunc && cd myfunc 
WHEN I run func build 
THEN I see some output which ensures me the process is still running 
AND I understand that the first time I run func build it may take a bit longer
```

**Comment by lance** [comment]
@omerbensaadon please have a look at this https://github.com/knative-sandbox/kn-plugin-func/pull/537

I think it should address this issue. It's not in a release yet, but will be in the next one.

**Comment by omerbensaadon** [comment]
I've updated the Acceptance Criteria... 

Can we ensure that we can fulfill #1? The only thing missing is letting users know that the first build will take longer than others.

**Comment by omerbensaadon** [comment]
I'll spin out AC #2 as it's own story

**Comment by lance** [comment]
> Can we ensure that we can fulfill #1? The only thing missing is letting users know that the first build will take longer than others.

I'll submit another PR that says as much on the first build.

**Comment by omerbensaadon** [comment]
@lance I've split this story up, see #555 

Also,  can we change "don't give up" to "don't give up on me" Naina and I think it's funnier
