### ISSUE TITLE
Change `func emit` to `func invoke`

### ISSUE THREAD

**Issue by omerbensaadon** [knative-sandbox/kn-plugin-func#576]
# Context
During the user interviews, we found that nearly everyone we talked to did not understand what "emit" did intuitively. 

We're going to go with `func invoke` instead as recommended by @lance 

---

# Story 

**As Deandra the Developer**
**I want** to have a more intuitive way to send CloudEvents to a running function
**So that** I more quickly understand what the purpose of `func emit` is 

# Acceptance Criteria

- [ ] `kn func invoke` works
```
GIVEN I leveraging the code which includes the PR that will close this issue  
WHEN I do kn func invoke 
THEN it directly mirrors the functionality of func emit 
```

---

- [ ] `kn func emit` doesn't
```
GIVEN I am testing my function
WHEN I execute `kn func emit` 
THEN it does not perform the intended action 
AND it issues a warning about `send` vs. `invoke` 
```

Some potential messaging: 

```
ERROR: kn func emit is not supported by kn func {current version #} and was deprecated in {version # of deprecation}

Did you mean kn func invoke?
```

**Comment by nainaz** [comment]
I like the command name "invoke" as send does not properly convey what are we sending and why and what it is the intent. 
kn func invoke removes this ambiguity. I am invoking my created function with the appropriate "trigger". 
P.S: emit/send/invoke command should cover the plain http call/test to the function as well. Should I create a different issue for that?

**Comment by lance** [comment]
> P.S: emit/send/invoke command should cover the plain http call/test to the function as well. Should I create a different issue for that?

As long as we are including multiple acceptance criteria in a single issue, I think it's OK as it is.

**Comment by omerbensaadon** [comment]
@lance am I understanding correctly that we want invoke to better cover HTTP templates and it currently only covers CloudEvents templates? 

If it's a small change, I can add an AC here. Feels to me like a new issue on first glance.

**Comment by lance** [comment]
> @lance am I understanding correctly that we want invoke to better cover HTTP templates and it currently only covers CloudEvents templates?

Yes exactly. I think I've covered the use cases here: https://github.com/knative-sandbox/kn-plugin-func/issues/575
