### ISSUE TITLE
Add examples as comments when creating func.yaml

### ISSUE THREAD

**Issue by rhuss** [knative-sandbox/kn-plugin-func#598]
It would be super awesome if some examples for how to customize func.yaml could be added as comments. Currently I want to customize the `envs` property but have no clue what to add as array. Of course, I can look it up (and will do), but having this directly in the gerated `func.yaml` as an example (in a yaml comment), that would be great.

Not sure how easy it is to implement this.

**Comment by lance** [comment]
Related to this, if you decide to comment your `func.yaml` to explain things to yourself, the next time you run a build, `kn func` will overwrite these comments.

**Comment by lance** [comment]
Closing in favor of https://github.com/knative-sandbox/kn-plugin-func/issues/603 which should encapsulate this request
