### ISSUE TITLE
Simplify Go CE func template signature

### ISSUE THREAD

**Issue by embano1** [knative-sandbox/kn-plugin-func#606]
I brought this up in one of the user interviews and couldn't find a note/issue in the docs here whether simplifying the CE handler template signature was already discussed (and why it was decided to keep the 12 signature options). So please excuse if this has been answered already.

Currently, the handler in the Go template for the `CloudEvents` type signature exposes (leaks) all 12 signature options from the underlying Go CE SDK: 

https://github.com/knative-sandbox/kn-plugin-func/blob/6385147e06bafc50107da49cdecd65bd152ab6fb/templates/go/cloudevents/handle.go#L13-L24

Picking the right option (signature) here is not only an additional step one has to make (and understand) but also increases the cognitive load to do the "right thing", especially for newcomers.

My feedback in the interview was to simplify the handler to `func(context.Context, event.Event) (*event.Event, error)` which captures all options and follows Go conventions, e.g. returning `nil,nil` if no response and/or error should be indicated. If I don't need any of the input parameters, I can simply `_` them.

Thoughts?

**Comment by embano1** [comment]
@lkingland as `func` gets more adoption I was wondering whether this should be tackled soon to not break too many users?

**Comment by lkingland** [comment]
It's perhaps worth noting that this change is not a breaking change, so it will not break any users.

A function signature can be changed at any time to any of those supported by the underlying CloudEvents library.
