### ISSUE TITLE
Stray manifest.yaml files in go/cloudevents and typescript/cloudevents

### ISSUE THREAD

**Issue by lance** [knative-sandbox/kn-plugin-func#626]
These should be removed. They are redundant.

**Comment by salaboy** [comment]
@lance do you mean these ones: 
- https://github.com/knative-sandbox/kn-plugin-func/blob/main/templates/go/cloudevents/manifest.yaml
- https://github.com/knative-sandbox/kn-plugin-func/blob/main/templates/typescript/cloudevents/manifest.yaml

So the ones that need to stay are the ones in the parent directory?
- https://github.com/knative-sandbox/kn-plugin-func/blob/main/templates/typescript/manifest.yaml
- https://github.com/knative-sandbox/kn-plugin-func/blob/main/templates/go/manifest.yaml

I am happy to check all the other projects if you confirm that we only need the ones in the parent directories.

**Comment by lance** [comment]
@salaboy yes - the only ones needed are in the parent directory.
