### ISSUE TITLE
[placeholder] Change text of `func create -c` to show users what the flags are for runtime and templates 

### ISSUE THREAD

**Issue by omerbensaadon** [knative-sandbox/kn-plugin-func#635]

**Comment by lance** [comment]
@omerbensaadon can you be a little more specific here? This is what the prompt looks like for language:

```
❯ func create -c foo
? Project path: /home/lanceball/src/github.com/knative-sandbox/kn-plugin-func/foo
? Runtime:  [Use arrows to move, type to filter]
  go
> nodejs
  python
  quarkus
  rust
  springboot
  typescript
```

And once you select it, you'll see this.

```
❯ ./func create -c foo
? Function Path: /home/lanceball/src/github.com/knative-sandbox/kn-plugin-func/foo
? Language Runtime: nodejs
? Template: [tab for suggestions] (http)
```
By hitting <TAB> it will provide you with all of the possible templates. What would you like to see that's different?

**Comment by lkingland** [comment]
This may not be the intention of the issue, but it does make me consider:
the `-c` flag is intended for first-time users or beginners.
It would be nice if we thought of it as "training wheels" to proper command-line usage.
If this is the goal, then the output from `-c` could be amended to always include, at the end, a message indicating how the process _could_ have been completed using a set of flags.
Again, that might not be the suggestion of this issue, but perhaps it is worth discussing nonetheless.

**Comment by lance** [comment]
> If this is the goal, then the output from `-c` could be amended to always include, at the end, a message indicating how the process _could_ have been completed using a set of flags.

+1

**Comment by lance** [comment]
@omerbensaadon @lkingland doing a little cleanup, and this issue is both quite stale, and not specific enough to be actionable. I'm going to close for now. Feel free to reopen or create a new request with more details if this still needs addressing.

**Comment by nainaz** [comment]
I like this idea of adding flag at the end to let users know about other flags. 
However, I agree, -c should be default unless user is using specific  flags. 
@lance @lkingland
