### ISSUE TITLE
Push container image should be an option in `func build`

### ISSUE THREAD

**Issue by salaboy** [knative-sandbox/kn-plugin-func#676]
While working on the Tekton Pipelines for onCluster builds I found that the push functionality is defined inside the `func deploy` command and that `func build` only does the building of the image. `func deploy` does the push if it is instructed to build the image as part of the deploy procedure. 

My recommendation would be to:
- Move the push functionality to build, with an optional parameter to do so
- If `func deploy` wants to call `func build` it can do it and it can specify the push parameter there. 

This will allow us to clearly define the functionality for both `func build` and `func deploy`.

**Comment by salaboy** [comment]
@lance @zroubalik I need some consensus on this.. do you see any issue with this proposed change? I am happy to do the work around this.. but I am not sure who else needs to be included in the discussion.

**Comment by salaboy** [comment]
Reference: https://github.com/salaboy/func-oncluster-build-experiments/blob/main/README.md

**Comment by zroubalik** [comment]
@salaboy makes sense +1 from me

**Comment by zroubalik** [comment]
Just note, `func build` should by default keep the current behaviour (ie. don't push)

**Comment by salaboy** [comment]
@zroubalik so.. the idea is to add push as an optional parameter to `fund build` and remove the push code from `func deploy`? right? @lance are you ok with this change? @lkingland do you have any opinions on this change?

**Comment by lance** [comment]
> the idea is to add push as an optional parameter to `fund build` and remove the push code from `func deploy`? right? @lance are you ok with this change?

Conceptually, we think of deployment as a single act which may comprise multiple steps, one of which is a push to a registry. Truthfully, this push should be an implementation detail that the function developer should not have to think about. But of course we are not there yet.

Personally, I think this is fine. Although it would be worth talking with Luke about it. A [pull request](https://github.com/knative-sandbox/kn-plugin-func/pull/79) of his last year removed the `--push` flag from build. There is a lot of discussion in the PR comments about that decision. Although, now I think that some of that reasoning may be aged to the point where we can revisit it.

**Comment by zroubalik** [comment]
We should at least do this change internally in the API and not expose to CLI.

**Comment by lance** [comment]
I think this was fixed in https://github.com/knative-sandbox/kn-plugin-func/pull/681
Closing as resolved
