### ISSUE TITLE
`func deploy` should only prompt build questions if `build` argument is set to `true`

### ISSUE THREAD

**Issue by salaboy** [knative-sandbox/kn-plugin-func#693]
Currently, even if you disable the build option for `func deploy` it still prompt questions related to the build phase. 

https://github.com/knative-sandbox/kn-plugin-func/blob/c2e1b769cc0d80082e6ef1be9ad2785ba8db4550/cmd/deploy.go#L114

I think this is just a bug.

**Comment by shinigambit** [comment]
It does look like a bug but unfortunately I haven't been able to reproduce it, could you share more information about the conditions you had when you experienced this? The contents of the `func.yaml` file and the command used would be of much help

**Comment by lance** [comment]
@shinigambit I was able to reproduce this with the following actions.

* `func create -l node test`
* `func build -p test --build disabled`

You need to be sure that you don't have `FUNC_REGISTRY` set in your environment. If you do, then it will just deduce the expected name of the function and attempt to deploy it, even though it has never been built. That's also probably an issue. But separate from this one.
