### ISSUE TITLE
`func deploy` will push the image even if the SHA in the `func.yaml` file is present

### ISSUE THREAD

**Issue by salaboy** [knative-sandbox/kn-plugin-func#695]
Related to #676 

`func deploy` should have a clear behaviour for deciding when to push a container image to the registry. 
Currently is always pushing: https://github.com/knative-sandbox/kn-plugin-func/blob/db9ad07c7048361946a8c7d45c549323eee44a58/client.go#L597

I do understand the need to collapse push and deploy together in benefit to a better user experience, but for integration tasks, deploy should just do a deploy. This can be achieved by a consistent set of arguments or env vars.

**Comment by embano1** [comment]
+1

Also the behavior is strange. If I explicitly disable `build`, why would it still try to push the specified image? `kn func deploy --build=false --image kind.local/my-image`
