### ISSUE TITLE
Users are not allowed to add environment variables without a cluster connection

### ISSUE THREAD

**Issue by jrangelramos** [knative-sandbox/kn-plugin-func#706]
Users are not allowed to use `func config envs` to ...

- add environment variables with specified value
- add environment variables from with value sourced from local environment variable

... when user is not connected to a cluster. The below error is thrown

```
$ func config envs add
Error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

I think at least these 2 operations should not require a real cluster connection. User should be able to do some local development and experiments with func without a real cluster.

**Comment by lance** [comment]
/remove-lifecycle stale
do it right this time
