### ISSUE TITLE
Unable to build functions on Windows using a remote docker daemon (thru TCP connection)

### ISSUE THREAD

**Issue by jrangelramos** [knative-sandbox/kn-plugin-func#720]
I'm unable to build functions on Windows environment (without docker) using a TCP connection pointing to a docker daemon running on linux (DOCKER_HOST = tcp://_LINUX_SERVER_IP_:_PORT_ )

The following error is observed:

```
←[31;1mERROR: ←[0mfailed to initialize docker client: failed to connect to docker socket: dial unix /var/run/docker.sock: connect: connection refused
```

**Comment by lance** [comment]
@jrangelramos is this still an issue?

**Comment by jrangelramos** [comment]
Hi @lance  the issue still persists. However it sounds to me that connection thru a TCP connection like that is a bad practice that should not be encouraged. So for that scenario (connect to a remote docker daeamon) using SSH connections should be the way to go by developers, so given that I'm closing this issue.
