### ISSUE TITLE
Allow push to internal registry

### ISSUE THREAD

**Issue by matejvasek** [knative-sandbox/kn-plugin-func#721]
Make it possible to push to cluster internal registries.

* User should be able to push to internal registry with cluster local URL
  (e.g. `image-registry.openshift-image-registry.svc:5000`).

* If needed the cluster internal CA should be trusted for the connection.

* If the cluster is OpenShift we should use it's internal registry by default, i.e. not prompt user for registry.

**Comment by matejvasek** [comment]
related PRs: #718, #704, #688.

**Comment by zroubalik** [comment]
@matejvasek this is done, right?
