### ISSUE TITLE
Clean up after `func run`

### ISSUE THREAD

**Issue by matejvasek** [knative-sandbox/kn-plugin-func#767]
If `func run` ends abruptly (e.g. `SIGKILL`) container is not cleaned up.

**Comment by matejvasek** [comment]
@mohitsuman what issue was this causing for IDE integration?

**Comment by mohitsuman** [comment]
@matejvasek This is the issue it concerns with https://github.com/redhat-developer/intellij-knative/issues/93

@lstocchi can you add some more details for this issue.

**Comment by matejvasek** [comment]
After some investigation I think the issues is not on `func`/`kn func` side.
https://github.com/redhat-developer/intellij-common/issues/135

**Comment by matejvasek** [comment]
@mohitsuman @lstocchi ^^^

**Comment by matejvasek** [comment]
https://github.com/redhat-developer/intellij-common/pull/136
