### ISSUE TITLE
Make `func create` more new-user-friendly

### ISSUE THREAD

**Issue by lance** [knative-sandbox/kn-plugin-func#768]
Via @lkingland 

> The `-c` flag is intended for first-time users or beginners.
It would be nice if we thought of it as "training wheels" to proper command-line usage.

Consider modifying the output from interactive mode to always include, at the end, a message indicating how the process could have been completed using a set of flags.

/kind feat

Related: https://github.com/knative-sandbox/kn-plugin-func/issues/635

/cc @omerbensaadon

**Comment by nainaz** [comment]
This issue is talking about modifying `create -c` flag. I still think that it should be default unless user is providing the appropriate flags.
