### ISSUE TITLE
`func version` does not match released version

### ISSUE THREAD

**Issue by jrangelramos** [knative-sandbox/kn-plugin-func#771]
The version informed by `func version` does not match the released version. Also the func.yaml version field is only updated with the actual version after a build.

```
$ curl -L https://github.com/knative-sandbox/kn-plugin-func/releases/download/v0.20.0/func_linux_amd64 -o func_v0.20.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   655  100   655    0     0  24784      0 --:--:-- --:--:-- --:--:-- 25192
100 64.9M  100 64.9M    0     0  13.6M      0  0:00:04  0:00:04 --:--:-- 14.5M
$ chmod 744 func_v0.20.0 
$ ./func_v0.20.0 create -l node /tmp/myfn
Created node Function in /tmp/myfn
$ head -1 /tmp/myfn/func.yaml 
version: 0.0.0
$ ./func_v0.20.0 build -p /tmp/myfn -r docker.io/jrangelramos
   🙌 Function image built: docker.io/jrangelramos/myfn:latest
$ head -1 /tmp/myfn/func.yaml 
version: 0.19.0
```

**Comment by jrangelramos** [comment]
Also version from `func version` is reported as 0.0.0

```
$ ./func_v0.20.0 version
v0.0.0
```

**Comment by senthilnathan** [comment]
Looks like it is trying to apply the migrations and ends up picking the version from [here](https://github.com/knative-sandbox/kn-plugin-func/blob/153e486bc62c05963cba41243d6c01a9f9ae414f/function_migrations.go#L76).

**Comment by lance** [comment]
> Looks like it is trying to apply the migrations and ends up picking the version from [here](https://github.com/knative-sandbox/kn-plugin-func/blob/153e486bc62c05963cba41243d6c01a9f9ae414f/function_migrations.go#L76).

Yes - the version itself is actually set in `func.yaml` by this code, which iterates over all "migrations" of the func.yaml file, applying them, and setting the version based on that migration. So in this case, I think it's not really a bug, because the purpose of this file is not to inform the user what version they are using, but rather what is the maximum version known-to-work with this func.yaml format.

I agree that it's confusing though. @lkingland wrote this code. Luke, can you chime in here?

**Comment by jrangelramos** [comment]
Hi @lance, thanks for confirmation I understand that.. meaning that's the minimal backward compatible version.. let's say a **func.yaml** created on func 0.20.0 is still compatible (an project can be build and deployed) with func 0.19.0. However when we use `func create` it saves the version on **func.yaml** as **0.0.0**. Shouldn't it be in this case **0.19.0** (the last compatible one)? 

Creating a **func.yaml** with 0.0.0 and then changing it to 0.19.0 during build... that's still confusing.

**Comment by lance** [comment]
@jrangelramos this issue covers both the version, when displayed with `func version` and the `version` field in func.yaml. Since the first issue has been resolved, I am going to close this and I have opened #861 to track the latter issue.
