### ISSUE TITLE
Improve `func version`, add build date and git revision

### ISSUE THREAD

**Issue by jrangelramos** [knative-sandbox/kn-plugin-func#784]
Here a suggestion of enhancement.
Include on `func version` information about build date and git revision of that build (similar to `kn version`)

Example:
```
$ func version
Version:      v0.20.0
Build Date:   2021-12-20 19:16:16
Git Revision: f20a238
```

**Comment by lkingland** [comment]
Thanks; this is working as expected. The default output from `func version` should be simply the semver tag, such that it is both simple, and easy to use in nontrivial commands (such as `diff`ing the versions of two binaries.  The data you're looking for is in `func version --help`:
```
Use the --verbose option to include the build date stamp and commit hash"
```
So, as with the other commands, the `-v` (`--verbose`) flag returns more information.  In this case it returns the requested information in an easily parseable hyphen-delimited value formatted as `[semver]-[git hash]-[timestamp]` with the timestamp being [ISO8601 UTC](https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC))

For example:
```
$ func version --verbose
vX.Y.Z-1f0c25e9-20220124T115442Z
```
If the git version built does not have a version tag, it is presumed to be a development build and the special version `tip` is used to indicate the "very tip of the currently active git tree", which may include commits not formally released yet.  You can see how this works yourself, if you're feeling curious, by building the latest tagged version:
```
$ git checkout $(git tag --sort=version:refname -l 'v0*' | tail -n1) && make
$ ./func version --verbose
v0.21.2-2acc4b78-20220131T061518Z
```
I hope that helps.
