### ISSUE TITLE
Update brew repo with func 0.19

### ISSUE THREAD

**Issue by lance** [knative-sandbox/kn-plugin-func#794]
Per @rhuss 
> Currently 0.18 is the latest release in https://github.com/knative-sandbox/homebrew-kn-plugins --> https://github.com/knative-sandbox/homebrew-kn-plugins/blob/main/func.rb#L4
> 
> In case of a func release this repo needs to be updated manually (by sending a PR with the updated version numbers, plus potentially copying over the original version to a func@0.18.rb like done for the version 0.17.

/kind bug

**Comment by xtreme-sameer-vohra** [comment]
Would it make sense to automate this since this will keep happening (eg. https://knative.slack.com/archives/CUU6LEMRT/p1644896058641159 and current released version is v0.21.2) ?

**Comment by lance** [comment]
@xtreme-sameer-vohra you're right! It should definitely be automated. For the time being, I've submitted a manually created PR. Thanks for reminding me of this issue!
