### ISSUE TITLE
Build error with Podman 3.4

### ISSUE THREAD

**Issue by matzew** [knative-sandbox/kn-plugin-func#808]
Following this guide:
https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/guides/podman.md

Getting the following after a successful build:

```bash
...
...
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building thin jar: /workspace/target/function-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1167ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  34.965 s
[INFO] Finished at: 2022-02-02T07:44:59Z
[INFO] ------------------------------------------------------------------------
===> EXPORTING
ERROR: failed to  image: error during connect: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.40/info": EOF
Error: executing lifecycle: failed with status code: 1
```

Podman:

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 22:45:07 2021
OS/Arch:      linux/amd64
```

**Comment by matejvasek** [comment]
https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/guides/podman.md#known-issues didn't help @matzew ?

Also with func +v0.20.0 you shouldn't need start service https://github.com/knative-sandbox/kn-plugin-func/pull/648

**Comment by matejvasek** [comment]
Also we should update https://github.com/knative-sandbox/kn-plugin-func/blob/main/templates/quarkus/manifest.yaml .

**Comment by matejvasek** [comment]
@matzew also maybe this may be workaround-ed by using `:tip` tag for your builder images in `func.yaml`.

**Comment by evanshortiss** [comment]
Seems like the link to the guide for using Podman with Func has changed. It's now: https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/reference/podman.md, just in case anyone sees the 404 like I did.

Changing to `quay.io/boson/faas-jvm-builder:tip` tag worked. Thanks @matejvasek

**Comment by lance** [comment]
@matejvasek @matzew I think this issue can probably be closed now as obsolete. wdyt?

**Comment by lance** [comment]
Ping @matejvasek @matzew wdyt - this can be closed, no?

**Comment by lance** [comment]
Closing - I think this has been fixed. Feel free to reopen with further details if not.
