### ISSUE TITLE
More schema validation errors for func.yaml

### ISSUE THREAD

**Issue by trisberg** [knative-sandbox/kn-plugin-func#811]
The latest fix in #805 resolved most of the issues from #804 but I'm still seeing these errors opening `func.yaml` in VS Code:

```
func.yaml
Source: [func_yaml-schema.json](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html#)

Missing property "build".yaml-schema: func.yaml
Missing property "git".yaml-schema: func.yaml
```

**Comment by zroubalik** [comment]
Those properties are present in the schema.json, you can check that yourselves: https://github.com/knative-sandbox/kn-plugin-func/blob/b4e6318ce5ec6bab1d48113c517221eb8d34744e/schema/func_yaml-schema.json#L67-L77

I don't see any errors in my VSCode (it is referencing the correct json (https://raw.githubusercontent.com/knative-sandbox/kn-plugin-func/main/schema/func_yaml-schema.json). It is more likely problem in your setup, referencing to some stale cached data.

**Comment by trisberg** [comment]
If I use the plugin to create a function I don't get those required fields in the YAML

**Comment by trisberg** [comment]
Also, If I add them, then validation passes but I  can't build the function

**Comment by zroubalik** [comment]
@trisberg that means that you are using old build of `func` binary. Please try the latest version from `main`.

**Comment by trisberg** [comment]
@zroubalik you're right, if I build the latest it works but not if I use the most recent release. Closing this for now.
