### ISSUE TITLE
Unable to run 'make' on project on macOS

### ISSUE THREAD

**Issue by trisberg** [knative-sandbox/kn-plugin-func#834]
If I try to build the project on macOS, then I'm getting an error when running `make`.

```
% make   
# Generating pkged.go using pkger
./hack/update-pkger.sh
./hack/../vendor/knative.dev/hack/library.sh: line 25: conditional binary operator expected
make: *** [pkged.go] Error 2
```

I believe this is due to macOS shipping an older version of `bash`

```
% bash -version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by lance** [comment]
Thanks for reporting this @trisberg - I think the best we can do here is find a good place in the documentation to note that a modern `bash` is required for contributors. Remarkably, the version shipped with MacOS is 15 years old! :roll_eyes: In case it helps, here is an article from a while back documenting one way to upgrade to a more recent version using `brew`. https://itnext.io/upgrading-bash-on-macos-7138bd1066ba

**Comment by trisberg** [comment]
strange thing, I'm not getting this any more, maybe it is not hitting that code path?

**Comment by lkingland** [comment]
The `./hack/update-pkger.sh` script which causes this issue does not actually use the library imported (the offending line).  I will also make a note to use the Makefile directly, as this script only adds an additional layer of complexity, potential breakage, and as we see here incompatibility.
