### ISSUE TITLE
Version in func.yaml is initially 0.0.0

### ISSUE THREAD

**Issue by lance** [knative-sandbox/kn-plugin-func#861]
But after first build it's set to 0.19.0. This could be quite confusing for users, even though we tend to say that func.yaml is not intended to be for users directly.

Related: https://github.com/knative-sandbox/kn-plugin-func/issues/771

```
❯ func create -l node foo
Created node Function in /home/lanceball/demo/foo

…shiftapps-com:6443/lball1 (lball1-dev) in ~/demo on   rh-serverless 
❯ head -1 foo/func.yaml 
version: 0.0.0

…shiftapps-com:6443/lball1 (lball1-dev) in ~/demo on   rh-serverless 
❯ func build -p foo
   🙌 Function image built: image-registry.openshift-image-registry.svc:5000/lball1-dev/foo:latest

…-com:6443/lball1 (lball1-dev) in ~/demo on   rh-serverless took 12s 
❯ head -1 foo/func.yaml
version: 0.19.0

…shiftapps-com:6443/lball1 (lball1-dev) in ~/demo on   rh-serverless 
❯ func version
v0.22.0

```

**Comment by lance** [comment]
@salaboy nope - still an issue

```
~/demo on ☁️  lanceball@gmail.com
❯ func create -l go foo
Created go Function in /Users/lball/demo/foo

~/demo on ☁️  lanceball@gmail.com
❯ head -1 foo/func.yaml

version: 0.0.0

~/demo on ☁️  lanceball@gmail.com
❯ func version
v0.24.0
```

**Comment by lance** [comment]
I wonder also... should the version in func.yaml equal the current version of the binary?

**Comment by lkingland** [comment]
The specific purpose of this version number is the last _migration_ which was applied, which is always the version number for which that migration applies.

There is nothing actually incorrect here (it's not a bug), but it does indeed cause confusion for a user looking at `func.yaml`.

The simple solution is to run migrations on `create`. None of the migrations will actually make any changes (the newly create Function is definitionally up to date), but it will populate the version field.

**Comment by lkingland** [comment]
If `compatibleAfter` is not immediatly obvious then I agree, `migration` (which carries no liguistic baggaage) would be good; or perhaps most accurately `lastAppliedMigration`... though that's a bit verbose.
Just getting away from `version` will be 90% confusion reduction

**Comment by zroubalik** [comment]
I am sorry, I missed this before.  I agree that `version` is confusing, though `migration` is confusing for me as well (as a non native speaker 😄 ).

What about `specVersion` instead of `version` ?

**Comment by lance** [comment]
I think `specVersion` could work @zroubalik - just modified #1086 to reflect this.
