### ISSUE TITLE
func create should offer a structured way of getting the list of templates and languages

### ISSUE THREAD

**Issue by jeffmaury** [knative-sandbox/kn-plugin-func#874]
As we use the func CLI as an API to create funtions in our tooling (VSCode / IntelliJ), the parameters are handled through UI (wizard,..) and we need the user to select the template before the CLI is invoked. So we should be able to retrieve the list of templates and languages

**Comment by jeffmaury** [comment]
A single command is to be preferred for performance reasons. Also structured output (JSON or YAML) is better for maintainability

**Comment by mohitsuman** [comment]
@lkingland I see we have PR #1114 merged and it mentions partially fixing this issue. Can you please let us know which features are covered in the PR and which are missing?

This will help the IDE integration to start the work on supporting this workflow of templates and repos.

**Comment by mohitsuman** [comment]
So the remaining bit is the list of templates as json output ?

**Comment by lance** [comment]
> So the remaining bit is the list of templates as json output ?

Yes, as far as I am aware. I'm not exactly sure if Luke has anything else in mind.

**Comment by lkingland** [comment]
That's right, the forthcoming `templates` command will function much the same way, including a structured list of templates _with_ their languages.
