### ISSUE TITLE
Springboot functions build takes too long

### ISSUE THREAD

**Issue by jrangelramos** [knative-sandbox/kn-plugin-func#880]
Hello Func team.
Spring boot default function created using `func create -l springboot myfunc` takes too long to build.
A performed a test on my machine it took 22m28s just for `func build`

As a comparison a **Quarkus** default function (also jvm/maven basedt) took **2m36s** under the same machine/conditions.

Maybe here is not the right location for this issue, but the idea is to raise a discussion about improvements that could be made to have this builder faster such as, review and fine tune pom.xml dependencies for SB bp or use a different customized paketo builder for SB functions.

**Comment by salaboy** [comment]
@jrangelramos yes... that's because it is using spring native builds by default.. there is an open PR that will fix that.. I will try to finish it today.

**Comment by salaboy** [comment]
@jrangelramos this is the right place for this discussion

**Comment by salaboy** [comment]
I think we can close this one now, as the template has been changed to use non-native build, which can be enabled again by setting an ENV variable for the buildpack. IF this is still a problem please reopen.
