### ISSUE TITLE
repo add seems broken on Windows

### ISSUE THREAD

**Issue by jeffmaury** [knative-sandbox/kn-plugin-func#894]
Using 0.22.0, I ran:

- `func repo add https://github.com/boson-project/templates`
- `func repo list`

But the last one gives me the following output:

`Error: parse "file://C:\\Users\\JeffMAURY\\.config\\func\\repositories/me": invalid port ":\\Users\\JeffMAURY\\.config\\func\\repositories" after host`

**Comment by matejvasek** [comment]
@jeffmaury I believe I fixed similar issue already. Could you please check latest `main` version?
