### ISSUE TITLE
func cli take a lot of time to execute any commands on latest version of macOS.

### ISSUE THREAD

**Issue by sudhirverma** [knative-sandbox/kn-plugin-func#899]
macOS version: 12.3
func version: 0.22.0

On the latest version of mac `func cli` takes a lot of time to execute any command.

**Comment by matejvasek** [comment]
@sudhirverma are you connected to running `k8s` cluster?

**Comment by lance** [comment]
@sudhirverma thanks for the response. I'm closing this now, feel free to open a new issue if you encounter any more problems on macos
