### ISSUE TITLE
Invoking a specific http endpoint requires func.yaml

### ISSUE THREAD

**Issue by lstocchi** [knative-sandbox/kn-plugin-func#906]
I don't know if this is a wanted behaviour or not. If so, it would be good to know the reasoning behind it so to customize the experience on IJ/vscode as we're adding support for the invoke action in our plugins.

In the tree i have access to all functions, the ones that have been deployed and those that are only opened locally.
When i invoke a remote function or one by using a custom endpoint i receive an error `Error: stat .....func.yaml: no such file or directory` because i don't have the project opened in my IDE.
So the question is, why does it require access to the function func.yaml file? I would expect it to work without needing to look for it. I'm only sending an event to a http endpoint and i'm passing to it all required args it needs, no?

**Comment by lance** [comment]
@lstocchi the `invoke` command will examine func.yaml to determine some information about the function being invoked. For example, it uses func.yaml to determine if the function should be invoked with a CloudEvent or just simple HTTP, among other things. For almost all `func` commands, the CLI uses the func.yaml file in this way. Typically, a user would be in their project directory, typing `func invoke` but I realize it's different in the IDE plugins. You can provide the `-p` or `--path` flag to tell the CLI where to look for it, and that should resolve the issue.

> So the question is, why does it require access to the function func.yaml file? I would expect it to work without needing to look for it. I'm only sending an event to a http endpoint and i'm passing to it all required args it needs, no?

I do agree it's odd that func.yaml is necessary for the case where you are providing everything, the endpoint URL, the data, etc. It should be possible in theory to remove that requirement, if a valid URL is provided, a payload is provided, etc. But `func` isn't really meant to be used as a general purpose networking tool. The `invoke` command does a decent amount of work to figure out what to send and where to send it based on the information in func.yaml. If the function has been deployed, it will invoke the function there unless `--target local` is set, for example.

By default, `func invoke` has some pretty nice behavior. It would be great if these defaults were reflected in the IDE as well. There is some pretty good documentation here https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/guides/commands.md#invoke and I am happy to answer any questions or continue the discussion.

**Comment by lstocchi** [comment]
Thanks @lance for the answer.

Yeah i was more focussed on a couple of scenarios when the user doesn't have access to the func.yaml of the deployed function. But this should be easily fixable by disabling the invoke action for the function which are not opened locally in the IDE.

These are the two scenarios

1) Let's say I'm working on a new function and i deploy it. Then i keep updating it locally and i use the invoke command to verify that the behavior of my new code is as expected. 
I face an issue and i want to check if the old version (the one i deployed before) has this kind of problem too. Ideally i would like to use the same invoke call.
But then maybe in my local repo i have a different `func.yaml` compared to the one I used for the deployed version. It could be a volume, env variable, label, name, something else i'm not aware. I don't know if this could change the call i'm making behind the hood.

2) I want to invoke the deployed function created by another guy and i don't have the source code and, so, the `func.yaml` used to invoke it.

**Comment by lstocchi** [comment]
Closing it. We fixed our issue by disabling the invoke action for functions which are not opened locally but visible in the tree because deployed on cluster.
