### ISSUE TITLE
Spring templates do not have a `test-templates` target in Makefile

### ISSUE THREAD

**Issue by lance** [knative-sandbox/kn-plugin-func#937]
Currently the Makefile does not have a target for `test-springboot`. And the tests appear to still expect string reversal instead of a simple echo.

/kind bug

**Comment by jrangelramos** [comment]
Hey @lance  see #959 and #970

That may interest too https://github.com/knative-sandbox/kn-plugin-func/runs/6025659288?check_suite_focus=true#step:8:1

**Comment by lance** [comment]
@jrangelramos excellent point - but I still think we should have a `test-springboot` target in the makefile that is triggered from `test-templates`.  When making changes to the templates, it would be nice to be able to run `make test-springboot` to validate them without having to wait for a full e2e.

**Comment by salaboy** [comment]
@lance thanks for doing this.. I will take care of this one
