### ISSUE TITLE
Image name overridden when deploying in openshift sandbox

### ISSUE THREAD

**Issue by lstocchi** [knative-sandbox/kn-plugin-func#941]
I'm trying to deploy a function to my sandbox cluster. I want to push the image to quay registry but the cli tries to use the private one. Is this a bug or it is normal? If so, why? Thanks :pray: 

The image field in func.yaml is empty before executing the command then it gets populated by `quay.io...` and then overridden.

```
func deploy -p '/home/luca/demo-func/func2203' -i quay.io/lstocchi/func2203:latest -n lstocchi-dev
   🙌 Function image built: image-registry.openshift-image-registry.svc:5000/lstocchi-dev/func2203:latest
Error: failed to get credentials: Get "https://image-registry.openshift-image-registry.svc:5000/v2/": failed to start dialer container: reason: ErrImagePull, message: rpc error: code = Unknown desc = reading manifest 1.7.4.2-r0 in docker.io/alpine/socat: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Comment by matejvasek** [comment]
Private cluster should be just default. If you explicitly set image by `-i quay.io/lstocchi/func2203:latest` then the image should be used. I seems to work for me. Could you please try with latest version?

**Comment by matejvasek** [comment]
> Private cluster should be just default. If you explicitly set image by `-i quay.io/lstocchi/func2203:latest` then the image should be used. I seems to work for me. Could you please try with latest version?

Nope. My bad. It's not works. It's a bug.

**Comment by matejvasek** [comment]
It seems that registry `-r` take precedence before image in config.

See https://github.com/knative-sandbox/kn-plugin-func/issues/506

When you are on OpenShift cluster then the `-r` flag is defaulted to internal registry.

Workaround for now: `func deploy -v -i quay.io/lstocchi/func2203:latest -r ''` -- explicitly set `-r` to empty string.
