### ISSUE TITLE
Credentials field gets overridden by "still building" message

### ISSUE THREAD

**Issue by lstocchi** [knative-sandbox/kn-plugin-func#974]
This issue is in cli v. 0.23/0.23.1. By using 0.22.0 everything works fine.

When trying to deploy a function and push the image in a private registry it asks for the credentials but the username field gets hidden and the `still building` message is visible. If you miss the moment when it asks for the username you don't know what's going on.

![error-deploy](https://user-images.githubusercontent.com/49404737/163985623-2e2f615a-b6d7-4fef-baf0-c2c69cbc2e83.gif)

**Comment by matejvasek** [comment]
This is weird. This issue should be present in both versions. You can avoid this by `-v` flag. @lstocchi

**Comment by lstocchi** [comment]
Thanks for the suggestion @matejvasek!! I'm going to use this workaround until this is fixed :+1:
