### ISSUE TITLE
Development Guide hyperlink 404's

### ISSUE THREAD

**Issue by bbtong** [knative-sandbox/kn-plugin-func#976]
The "Development Guide" hyperlink in the initial README docs 404. It is not clear where to go instead to learn how to participate.

**Comment by lance** [comment]
@bbtong we recently rearranged the docs and it seems some links were missed. Here is the developer's guide. https://github.com/knative-sandbox/kn-plugin-func/blob/main/docs/function-developers/developers_guide.md

**Comment by bbtong** [comment]
@lance Thanks!
