### ISSUE TITLE
Deleting functions on OSD shows error messages related to Tekton pipelines

### ISSUE THREAD

**Issue by lance** [knative-sandbox/kn-plugin-func#986]
A deployed function, when deleted, will show error messages if the user does not have proper permissions. For example on the Developer Sandbox, this error message is displayed.

```
Error: error deleting resources:
 pipelines.tekton.dev is forbidden: User "lball1" cannot deletecollection resource "pipelines" in API group "tekton.dev" at the cluster scope
 pipelineruns.tekton.dev is forbidden: User "lball1" cannot deletecollection resource "pipelineruns" in API group "tekton.dev" at the cluster scope
 rolebindings.rbac.authorization.k8s.io is forbidden: User "lball1" cannot deletecollection resource "rolebindings" in API group "rbac.authorization.k8s.io" in the namespace "lball1-dev"
```

I suspect this will be an issue for most multi-tenant environments.

/kind bug
/cc @zroubalik

**Comment by zroubalik** [comment]
@lance are you sure you are using the latest `func`?

**Comment by lance** [comment]
> @lance are you sure you are using the latest `func`?

I will try confirming later today.

**Comment by lance** [comment]
@zroubalik this is with a binary built from `main`

**Comment by zroubalik** [comment]
That's really strange, because we don't delete any rolebindings:
https://github.com/knative-sandbox/kn-plugin-func/blob/bed3dfc9f6bc03b845936e28099ae581d54c97e8/pipelines/tekton/pipeplines_provider.go#L174-L178

It was present in the previous code, but I removed this in on of the latests iteration.

**Comment by lance** [comment]
@zroubalik sorry - the original report was with an older version. I re-ran with `main` and didn't actually notice the difference (that rolebinding error was no longer there). This is what I see with `main`.

```
❯ func delete
🕛 Removing Knative Service 'viewer' and all dependent resources
Error: knative remover failed to delete the service: timeout: service 'viewer' not ready after 120 seconds
error deleting resources:
 pipelineruns.tekton.dev is forbidden: User "lball1" cannot deletecollection resource "pipelineruns" in API group "tekton.dev" in the namespace "lball1-dev"
 pipelines.tekton.dev is forbidden: User "lball1" cannot deletecollection resource "pipelines" in API group "tekton.dev" in the namespace "lball1-dev"
```
